client: ApplicationClass.o CameraClass.o ColorshaderClass.o InputClass.o Main.o ModelClass.o OpenglClass.o SystemClass.o
	g++ -o client ApplicationClass.o CameraClass.o ColorshaderClass.o InputClass.o Main.o ModelClass.o OpenglClass.o SystemClass.o -l GL -l X11

ApplicationClass.o: ApplicationClass.cpp
	g++ -c ApplicationClass.cpp

CameraClass.o: CameraClass.cpp
	g++ -c CameraClass.cpp

ColorshaderClass.o: ColorshaderClass.cpp
	g++ -c ColorshaderClass.cpp

InputClass.o: InputClass.cpp
	g++ -c InputClass.cpp

Main.o: Main.cpp
	g++ -c Main.cpp

ModelClass.o: ModelClass.cpp
	g++ -c ModelClass.cpp

OpenglClass.o: OpenglClass.cpp
	g++ -c OpenglClass.cpp

SystemClass.o: SystemClass.cpp
	g++ -c SystemClass.cpp
